kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ratings-web-https
  namespace: ratingsapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    # kubernetes.io/ingress.allow-http: 'false'
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - <fqdn>
      secretName: aks-tls-akv
  rules:
  - host: <fqdn>
    http:  
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ratings-web
            port: 
              number: 80