apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    azure.workload.identity/use: "true"
    service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/azure-open-ai-embeddings-qna-default: "true"
        service: api
    spec:
      serviceAccountName: serversa
      volumes:
        - name: secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: openaiapikey
      containers:
        - image: redis/redis-stack-server:latest
          name: api
          env:
            - name: REDIS_ARGS
              valueFrom:
                configMapKeyRef:
                  key: REDIS_ARGS
                  name: env
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: env
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -h
                - localhost
                - -p
                - "6379"
                - ping
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 90
          volumeMounts:
          - name: secrets-mount
            mountPath: "/mnt/secrets-store"
            readOnly: true
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
