apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - networkpolicy.yaml
  - batch-deployment.yaml
  - batch-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  
