# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ratings-web-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt
# spec:
#   tls:
#     - hosts:
#       - frontend.20-83-82-8.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
#       secretName: ratings-web-cert
#   rules:
#   - host: frontend.20-83-82-8.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
#     http:
#       paths:
#       - backend:
#           serviceName: ratings-web
#           servicePort: 80
#         path: /


# apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings-web
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: 
    http:
      paths:
       - backend:
          service:
            name: ratings-web
            port:
              number: 80
          path: /
          pathType: Exact
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: ratings-web
#           servicePort: 80