name: Maintenance - Check Markdown Quality

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  MustPass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: streetsidesoftware/cspell-action@v2.12.1
        name: Spell Check
        with:
          config: './.vscode/cspell.json'
          inline: warning
          root: '.'
          files: "**/*.{ts,js,md}" #You need to respecify this setting - even though it's in the cspell.json config :(
          incremental_files_only: false
          strict: true #setting to false allows the build to continue even if spelling mistakes are detected